name: "Hello Actions"
description: "Greet someone"
author: "mouctarbarry@github.com"

on:
  workflow_dispatch:
    inputs:
      MY_NAME:
        description: "Who to greet"
        required: true
        default: "World"

runs:
  uses: "docker"
  image: "docker://mouctarbarry/hello-action:latest"

branding:
  icon: "mic"
  color: "purple"