name: "Hello Actions"
on:
  workflow_dispatch:
    inputs:
      MY_NAME:
        description: "Who to greet"
        required: true
        default: "World"
  push:
    branches:
      - main

jobs:
  hello-actions-job:
    runs-on: ubuntu-latest
    container:
      image: docker://mouctarbarry/hello-action:latest
      options: --cpus 1
    env:
      MY_NAME: ${{ github.event.inputs.MY_NAME }}
    steps:
      - name: Run Hello Actions
        run: echo "Hello, $MY_NAME, from the Dockerized action!"
